# Generated by Django 4.1.5 on 2023-01-16 04:46

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=15)),
                ('Contrasena', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_Emp', models.IntegerField(verbose_name=builtins.max)),
                ('Genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('B', 'Prefiero no responder'), ('O', 'Otro')], default='O', max_length=20)),
                ('Fecha_Registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
