# Generated by Django 4.1.5 on 2023-01-16 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managmentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='Contrasena',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='Fecha_Registro',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='Genero',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='Num_Emp',
        ),
    ]
