# Generated by Django 4.1.5 on 2023-01-16 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managmentapp', '0002_remove_administrador_contrasena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='Clave',
            field=models.CharField(default='Password', max_length=15),
        ),
        migrations.AddField(
            model_name='administrador',
            name='Usuario',
            field=models.CharField(default='Admin', max_length=15),
        ),
        migrations.AddField(
            model_name='empleados',
            name='Apellido',
            field=models.CharField(default='Escriba su apellido', max_length=50),
        ),
        migrations.AddField(
            model_name='empleados',
            name='Fecha_Registro',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empleados',
            name='Genero',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('B', 'Prefiero no responder'), ('O', 'Otro')], default='O', max_length=20),
        ),
        migrations.AddField(
            model_name='empleados',
            name='Nombre',
            field=models.CharField(default='Escriba su nombre', max_length=50),
        ),
        migrations.AddField(
            model_name='empleados',
            name='Num_Emp',
            field=models.IntegerField(default=0),
        ),
    ]
