# Generated by Django 4.1.5 on 2023-01-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managmentapp', '0003_administrador_clave_administrador_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='Genero',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Desconocido', 'Sin respuesta'), ('Otro', 'Otro')], default='O', max_length=20),
        ),
    ]
