# Generated by Django 4.1.5 on 2023-01-18 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managmentapp', '0004_alter_empleados_genero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
